### ISSUE TITLE
retry needed for database operations

### ISSUE THREAD

**Issue by eastham** [eastham/adsb_actions#3]
@harpermann-lbl noticed that sometimes the database operations fail, we probably need to add a retry.

**Comment by harpermann** [comment]
Problem seems to be related to input restrictions on AppSheet dB limiting aircraft registration to N and C numbers.  Maybe remove the restriction.  Also, we seem to be getting flight numbers instead of tail numbers in the dB op which don't start with N or C.

INFO:root:Takeoff detected! DLH459
WARNING:db.appsheet_api:add_aircraft op raised exception: op returned non-200 code: <Response [400]>

**Comment by harpermann** [comment]
From running op_pusher, the errors were from a restriction on the Appsheet dB where aircraft other than US or Canada are restricted and fail to record.  HP removed the restriction.  We now have alerts in place for write / read errors to Appsheet so won't add a retry unless we see another failure mode that requires it.
